### ISSUE TITLE
Problem importing file: File does not exist: data.dat (102) 

### ISSUE THREAD

**Issue by zj2050** [epignosis/efront_open_source#10]
@pvenakis @makriria 
sorry to trouble

where import lesson file  it show error :  Problem importing file: File does not exist: data.dat (102) 
can any way to solute it ?

i have set dir to everyone full control

thanks

**Comment by makriria** [comment]
@zj2050 import lesson process means to import lesson content that is exported from another eFront lesson. Not to add/create lesson. Have you an exported lesson zip file that you tried to import there?

**Comment by zj2050** [comment]
@makriria thanks quick reply
I add/create a new lesson , but how can submit new lesson document or lesson file ? , i really not find any way to do it  , was install wrong ?

my demo site :  lms.uxue100.com
acount : wendao   , pass : wd1234

thanks

**Comment by zj2050** [comment]
thank @makriria
