### ISSUE TITLE
Multiple CSRF vulnerabilities in eFront v. 3.6.15.2 (build 18021, released 5th Dec 2014)

### ISSUE THREAD

**Issue by sroesemann** [epignosis/efront_open_source#7]
Dear developer team.

I found multiple CSRF vulnerabilities in eFront v. 3.6.15.2, which could be abused by an attacker to put the security/integrity of an eFront installation in risk.

Could you please provide me an email-address where I can report the technical details of the issue to?

I published a security advisory on my blog (without technical details). See http://sroesemann.blogspot.de/2015/01/sroeadv-2015-09.html. 

If you will not respond until the 29th January 2015, I will as well publish the technical details and post the issue on the security-mailinglist FullDisclosure.

 Thank you very much.

Steffen Rösemann

**Comment by pvenakis** [comment]
Hello,
can you please send an email at tech@efrontlearning.net detailing your findings? We'll be happy to work with you to resolve these vulnerabilities

**Comment by sroesemann** [comment]
Done a minute ago! :-)

**Comment by sroesemann** [comment]
Fixed by developers in eFront v. 3.6.15.3 build 18022, released 30th January 2015. See here: http://www.efrontlearning.net/download
